# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# C:\b\abs_a638z6l1z0\clone\recipe, last modified Fri Jun 30 09:36:05 2023
# ------------------------------------------------

package:
  name: nltk
  version: 3.8.1
source:
  sha256: 1834da3d0682cba4f2cede2f9aad6b0fafb6461ba451db0efb6f9c39798d64d3
  url: https://pypi.io/packages/source/n/nltk/nltk-3.8.1.zip
build:
  entry_points:
    - nltk = nltk.cli:cli
  number: '0'
  script: C:\\b\\abs_a638z6l1z0\\croot\\nltk_1688114186909\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.05.30 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.9 h2bbff1b_0
    - pip 23.1.2 py311haa95532_0
    - python 3.11.3 he1021f5_1
    - setuptools 67.8.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py311haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - click
    - joblib
    - python >=3.11,<3.12.0a0
    - regex >=2021.8.3
    - tqdm
test:
  commands:
    - pip check
    - nltk -h
  imports:
    - nltk
    - nltk.app
    - nltk.ccg
    - nltk.chat
    - nltk.chunk
    - nltk.classify
    - nltk.cluster
    - nltk.corpus
    - nltk.corpus.reader
    - nltk.draw
    - nltk.inference
    - nltk.lm
    - nltk.metrics
    - nltk.misc
    - nltk.parse
    - nltk.sem
    - nltk.sentiment
    - nltk.stem
    - nltk.tag
    - nltk.tbl
    - nltk.test
    - nltk.test.unit
    - nltk.test.unit.translate
    - nltk.tokenize
    - nltk.translate
    - nltk.twitter
  requires:
    - colorama
    - pip
about:
  description: 'NLTK has been called a wonderful tool for teaching and working in

    computational linguistics using Python and an amazing library to play with

    natural language.

    '
  dev_url: https://github.com/nltk/nltk
  doc_url: https://www.nltk.org/
  home: https://www.nltk.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Natural Language Toolkit
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a625aab1-8a00-40b9-a6bb-be7f3222f861
  recipe-maintainers:
    - pmlandwehr
    - quartox
  remote_url: git@github.com:AnacondaRecipes/nltk-feedstock.git
  sha: 298e4996390e4e4eee22fe613df49285158b7b40
